language: go

go:
  - 1.4
  - 1.5
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"
script:
  - go get -u github.com/golang/lint/golint
  - golint ./marshal/...
  - test `gofmt -l . | wc -l` = 0
  - go test -race ./marshal/...

install:
  - go get -v -t ./marshal

matrix:
    allow_failures:
        - go: tip
        - go: 1.4
